api:
  prefix: /api/buyer

server:
  port: 8020

spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate

  jwt:
    secret: ENC(AJv6LokZXWCLSDdDEFT1UGe19935JohjmPnbyDPFNQWa+WgVgEaBrsg3Fo8Xo8Myj3KHBd5e5Ka5pLS8nyOm2NNBdvwSAbjfBlpcZENOkyA=)

jasypt:
  encryptor:
    password: ${key}
    bean: jasyptEncryptor

ncp:
  object-storage:
    endpoint: https://kr.object.ncloudstorage.com
    region: kr-standard
    bucket: bitcamp-68

  image:
    product:
      path: https://zcbg41sa9729.edge.naverncp.com/O8XfcLSSm6/product/
      type: ?type=h&h=192&ttype=png
    banner:
      path: https://zcbg41sa9729.edge.naverncp.com/O8XfcLSSm6/
      type: ?type=m&w=1320&h=300&quality=90&bgcolor=FFFFFF&ttype=jpg&anilimit=1
    event:
      path: https://zcbg41sa9729.edge.naverncp.com/O8XfcLSSm6/
      type: ?type=m&w=750&h=2000&quality=90&bgcolor=FFFFFF&ttype=jpg&anilimit=1
    review:
      path: https://zcbg41sa9729.edge.naverncp.com/O8XfcLSSm6/
      type: ENC(alzL6HsotGrLyKnB9lckv9IqIIAxF5TEja2+KzRNDNp1Vua4fGenWaDjzZK8yzML)

  image-optimizer:
    project-id: O8XfcLSSm6
    cdn-domain: zcbg41sa9729.edge.naverncp.com

  access-key: ENC(Qt6csgd6ac5Yu+d9oLMMjBL19hWZzMIJk722uWb+NAVwki8xPWPJ5Q==)
  secret-key: ENC(NJyd1B45LLe/rZ29jbO4SfS434rjGNGH2LbZIjIePLpZiFMwu7ixGlOOEZthqSczvzw0Cb85k0M=)

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always