spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate

ncp:
  object-storage:
    endpoint: https://kr.object.ncloudstorage.com
    region: kr-standard
    bucket: farmdora

  image:
    path: https://zcbg41sa9729.edge.naverncp.com/O8XfcLSSm6/product/
    type: ?type=h&h=192&ttype=png

  image-optimizer:
    project-id: Gv9VppsiR9
    cdn-domain: aacblnby9780.edge.naverncp.com

  access-key: ncp_iam_BPASKR5nKujGrW7C2yV5
  secret-key: ncp_iam_BPKSKRPXwNzYCHv9zMJfroeR2XA8e47gQv